# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_kaspi_1', '0004_auto_20161117_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='vid',
        ),
        migrations.AddField(
            model_name='venue',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_kaspi_1.Tip'),
        ),
    ]
