# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_kaspi_1', '0007_auto_20161118_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='name',
            new_name='name_tip',
        ),
    ]
